#if !canImport(ObjectiveC)
import XCTest

extension ArgumentsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArgumentsTests = [
        ("testArgument", testArgument),
        ("testCommand", testCommand),
        ("testFlag", testFlag),
        ("testMissing", testMissing),
        ("testOption", testOption),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArgumentsTests.__allTests__ArgumentsTests),
    ]
}
#endif
